KIND:       Endpoints
VERSION:    v1

DESCRIPTION:
    Endpoints is a collection of endpoints that implement the actual service.
    Example:
    
    	 Name: "mysvc",
    	 Subsets: [
    	   {
    	     Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
    	     Ports: [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
    	   },
    	   {
    	     Addresses: [{"ip": "10.10.3.3"}],
    	     Ports: [{"name": "a", "port": 93}, {"name": "b", "port": 76}]
    	   },
    	]
    
FIELDS:
  apiVersion	<string>
  kind	<string>
  metadata	<ObjectMeta>
    annotations	<map[string]string>
    creationTimestamp	<string>
    deletionGracePeriodSeconds	<integer>
    deletionTimestamp	<string>
    finalizers	<[]string>
    generateName	<string>
    generation	<integer>
    labels	<map[string]string>
    managedFields	<[]ManagedFieldsEntry>
      apiVersion	<string>
      fieldsType	<string>
      fieldsV1	<FieldsV1>
      manager	<string>
      operation	<string>
      subresource	<string>
      time	<string>
    name	<string>
    namespace	<string>
    ownerReferences	<[]OwnerReference>
      apiVersion	<string> -required-
      blockOwnerDeletion	<boolean>
      controller	<boolean>
      kind	<string> -required-
      name	<string> -required-
      uid	<string> -required-
    resourceVersion	<string>
    selfLink	<string>
    uid	<string>
  subsets	<[]EndpointSubset>
    addresses	<[]EndpointAddress>
      hostname	<string>
      ip	<string> -required-
      nodeName	<string>
      targetRef	<ObjectReference>
        apiVersion	<string>
        fieldPath	<string>
        kind	<string>
        name	<string>
        namespace	<string>
        resourceVersion	<string>
        uid	<string>
    notReadyAddresses	<[]EndpointAddress>
      hostname	<string>
      ip	<string> -required-
      nodeName	<string>
      targetRef	<ObjectReference>
        apiVersion	<string>
        fieldPath	<string>
        kind	<string>
        name	<string>
        namespace	<string>
        resourceVersion	<string>
        uid	<string>
    ports	<[]EndpointPort>
      appProtocol	<string>
      name	<string>
      port	<integer> -required-
      protocol	<string>
      enum: SCTP, TCP, UDP

