apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restarts-alert
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
    - name: api
      rules:
        - alert: IntegrationRuntimeNotStarted 
          expr: max_over_time(kube_pod_container_status_waiting_reason{job="kube-state-metrics",namespace="boa-app",reason="CrashLoopBackOff"}[5m]) * 60 * 5 > 0
          for: 1m
          labels:
            severity: critical
            job: cpu-not-set   
            namespace: monitoring           
          annotations:
            summary: |
              "Following  IntegrationRuntimes in the environment {{ $labels.namespace }}. are not started"
            description: |
              "CPU Limit has not set for the IntegrationRuntime related to the pod {{ $labels.pod }} 
              in namespace {{ $labels.namespace }}."
        - alert: CPULimitNotSet
          expr: count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!="", namespace="boa-app"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource="cpu"})) == 0
          for: 1m
          labels:
            severity: critical
            job: cpu-not-set   
            namespace: monitoring           
          annotations:
            summary: |
              "CPU Limit has not set for the IntegrationRuntime 
              in namespace {{ $labels.namespace }}."
            description: |
              "CPU Limit has not set for the IntegrationRuntime related to the pod {{ $labels.pod }} 
              in namespace {{ $labels.namespace }}."
        - alert: PodRestarts
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed", namespace="boa-app"}) >= 0 
          for: 1m
          labels:
            severity: critical
            job: pod-restarts   
            namespace: monitoring           
          annotations:
            summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has more than 5 restarts"
            description: "The pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has experienced more than 5 restarts."