apiVersion: v1
kind: Service
metadata:
  name: service-metrics
  namespace: api-monitor
  labels:
    app: metrics-app
spec:
  type: NodePort
  ports:
    - name: "http"
      targetPort: 5000
      port: 5000
  selector:
    app: metrics-app
